### ISSUE TITLE
♻️ : replace docker-client with other lib

### ISSUE THREAD

**Issue by juwit** [gaia-app/gaia#47]
Spotify has discontinued support of docker-client.

We may need to use another lib, or wait for a valuable fork to be created.

**Comment by cdubuisson** [comment]
I just encountered an issue with the current docker client. 

On Arch Linux, with the lib `containerd` up to date (v1.3.0), which is a dependency for docker, I was unable to run successfully tests using TestContainer.

```
16:28:05.566 [ducttape-0] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 39f9840a1ec443ae273a30bdab1f59e2411d1e41f3ac92da11e048424fe2100d,<null>,true,true,<null>,<null>,<null>,{/bin/sh,-c,true &&  (cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :6989 || nc -vz -w 1 localhost 27017 || /bin/bash -c '</dev/tcp/localhost/27017')},<null>,<null>,com.github.dockerjava.core.exec.ExecCreateCmdExec@64df9bc3
16:28:05.990 [ducttape-0] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 8312bf8ad596dab56153d30f7cea06f4604ccbb44f76c5ae446d402a66aee6f9,com.github.dockerjava.core.exec.InspectExecCmdExec@6e5336f2
16:28:05.991 [ducttape-0] DEBUG com.github.dockerjava.core.exec.InspectExecCmdExec - GET: OkHttpWebTarget(okHttpClient=org.testcontainers.shaded.okhttp3.OkHttpClient@1272b8da, baseUrl=http://docker.socket/, path=[/exec/8312bf8ad596dab56153d30f7cea06f4604ccbb44f76c5ae446d402a66aee6f9/json], queryParams={})
16:28:06.993 [ducttape-0] DEBUG org.testcontainers.containers.ExecInContainerPattern - /clever_curran: Running "exec" command: /bin/sh -c true &&  (cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :6989 || nc -vz -w 1 localhost 27017 || /bin/bash -c '</dev/tcp/localhost/27017')
16:28:06.993 [ducttape-0] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 39f9840a1ec443ae273a30bdab1f59e2411d1e41f3ac92da11e048424fe2100d,<null>,true,true,<null>,<null>,<null>,{/bin/sh,-c,true &&  (cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :6989 || nc -vz -w 1 localhost 27017 || /bin/bash -c '</dev/tcp/localhost/27017')},<null>,<null>,com.github.dockerjava.core.exec.ExecCreateCmdExec@4d3b93c5
16:28:07.437 [ducttape-0] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 5a4cc132e690978f43681f4d4c653ee54a456d68c501e8930d02f7c6b306a809,com.github.dockerjava.core.exec.InspectExecCmdExec@7d0f986d
16:28:07.438 [ducttape-0] DEBUG com.github.dockerjava.core.exec.InspectExecCmdExec - GET: OkHttpWebTarget(okHttpClient=org.testcontainers.shaded.okhttp3.OkHttpClient@1272b8da, baseUrl=http://docker.socket/, path=[/exec/5a4cc132e690978f43681f4d4c653ee54a456d68c501e8930d02f7c6b306a809/json], queryParams={})
16:28:08.440 [ducttape-0] DEBUG org.testcontainers.containers.ExecInContainerPattern - /clever_curran: Running "exec" command: /bin/sh -c true &&  (cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :6989 || nc -vz -w 1 localhost 27017 || /bin/bash -c '</dev/tcp/localhost/27017')
16:28:08.440 [ducttape-0] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 39f9840a1ec443ae273a30bdab1f59e2411d1e41f3ac92da11e048424fe2100d,<null>,true,true,<null>,<null>,<null>,{/bin/sh,-c,true &&  (cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :6989 || nc -vz -w 1 localhost 27017 || /bin/bash -c '</dev/tcp/localhost/27017')},<null>,<null>,com.github.dockerjava.core.exec.ExecCreateCmdExec@29856616
16:28:08.881 [ducttape-0] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 2cf5895bd6699b8abe26f4b190269d8a12359fe4f7e156ba7c7cfdab9986995d,com.github.dockerjava.core.exec.InspectExecCmdExec@44630b6f
16:28:08.881 [ducttape-0] DEBUG com.github.dockerjava.core.exec.InspectExecCmdExec - GET: OkHttpWebTarget(okHttpClient=org.testcontainers.shaded.okhttp3.OkHttpClient@1272b8da, baseUrl=http://docker.socket/, path=[/exec/2cf5895bd6699b8abe26f4b190269d8a12359fe4f7e156ba7c7cfdab9986995d/json], queryParams={})
16:28:09.883 [ducttape-0] DEBUG org.testcontainers.containers.ExecInContainerPattern - /clever_curran: Running "exec" command: /bin/sh -c true &&  (cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :6989 || nc -vz -w 1 localhost 27017 || /bin/bash -c '</dev/tcp/localhost/27017')
16:28:09.884 [ducttape-0] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 39f9840a1ec443ae273a30bdab1f59e2411d1e41f3ac92da11e048424fe2100d,<null>,true,true,<null>,<null>,<null>,{/bin/sh,-c,true &&  (cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :6989 || nc -vz -w 1 localhost 27017 || /bin/bash -c '</dev/tcp/localhost/27017')},<null>,<null>,com.github.dockerjava.core.exec.ExecCreateCmdExec@75adbba1
16:28:10.328 [ducttape-0] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 4cfe21ca20d82d9b1daef9c9485f5c0a3c6c29c7c498bcef3bb932394981f3f6,com.github.dockerjava.core.exec.InspectExecCmdExec@1da9a571
16:28:10.328 [ducttape-0] DEBUG com.github.dockerjava.core.exec.InspectExecCmdExec - GET: OkHttpWebTarget(okHttpClient=org.testcontainers.shaded.okhttp3.OkHttpClient@1272b8da, baseUrl=http://docker.socket/, path=[/exec/4cfe21ca20d82d9b1daef9c9485f5c0a3c6c29c7c498bcef3bb932394981f3f6/json], queryParams={})
16:28:11.330 [ducttape-0] DEBUG org.testcontainers.containers.ExecInContainerPattern - /clever_curran: Running "exec" command: /bin/sh -c true &&  (cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :6989 || nc -vz -w 1 localhost 27017 || /bin/bash -c '</dev/tcp/localhost/27017')
16:28:11.330 [ducttape-0] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 39f9840a1ec443ae273a30bdab1f59e2411d1e41f3ac92da11e048424fe2100d,<null>,true,true,<null>,<null>,<null>,{/bin/sh,-c,true &&  (cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :6989 || nc -vz -w 1 localhost 27017 || /bin/bash -c '</dev/tcp/localhost/27017')},<null>,<null>,com.github.dockerjava.core.exec.ExecCreateCmdExec@244e9a16
16:28:11.489 [ForkJoinPool-1-worker-3] ERROR 🐳 [mongo:4.0] - Could not start container
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [32769] should be listening)
	at org.testcontainers.containers.wait.strategy.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:49)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.containers.wait.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:23)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:675)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:332)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:285)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:283)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:272)
	at io.codeka.gaia.test.MongoContainer.start(MongoContainer.java:41)
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.start(TestcontainersExtension.java:173)
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.access$100(TestcontainersExtension.java:160)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$null$1(TestcontainersExtension.java:41)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$getOrComputeIfAbsent$0(ExtensionValuesStore.java:81)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.get(ExtensionValuesStore.java:182)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.getOrComputeIfAbsent(ExtensionValuesStore.java:84)
	at org.junit.jupiter.engine.execution.NamespaceAwareStore.getOrComputeIfAbsent(NamespaceAwareStore.java:53)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$beforeAll$2(TestcontainersExtension.java:41)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.beforeAll(TestcontainersExtension.java:41)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassBasedTestDescriptor.java:353)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:353)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:187)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:77)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:115)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
It seems that the client is no more compatible with the latest version of `containerd`.
**To fix this, I had to downgrade `containerd` to v1.2.9**
